### ISSUE TITLE
Move to GHA

### ISSUE THREAD

**Issue by RalfJung** [rust-lang/miri-test-libstd#3]
It looks like Travis stopped running cron jobs a few weeks ago (the last build is from 2021-06-09, even though the settings claim the cron job triggered "9 hours ago").

That's one failure too much for Travis, so I guess it is time to move to GHA. To still be notified of cron job failues, we need our own communication channel as GHA does not support notifications. In Miri we are sending messages to Zulip, I hope we can do the same here. (The Miri repo has some CI secrets set so that it can send Zulip messages.) @pietroalbini what do I have to do to be able to send Zulip notifications from GHA jobs in this repo? Does it need to move to rust-lang?

**Comment by RalfJung** [comment]
Or maybe @Mark-Simulacrum is the right person to ping about this, not sure.

**Comment by Mark-Simulacrum** [comment]
I think if we want to push messages to rust-lang Zulip this repository should move to the rust-lang org as a prerequisite, yes.

Happy to get that process kicked off, this seems like a reasonable thing for us to have in-org; certainly we try to make sure that std/core/alloc are miri-compatible. It may even make sense to see if we can push these tests into rust-lang/rust's CI, conditional on Miri passing tests or so. Does that seem potentially desirable? I feel like I would've already talked about this...

**Comment by RalfJung** [comment]
Happy to move this in-org. What do I need to do for that?

>  It may even make sense to see if we can push these tests into rust-lang/rust's CI, conditional on Miri passing tests or so. Does that seem potentially desirable?

Yes, but my plan was to do this once we made Miri "always work", i.e., once it is a subtree... which I've been holding off on because the git subtree fixes required for that are still not upstream... :/

**Comment by Mark-Simulacrum** [comment]
Hm, it seems like subtree or not we'd run the tests just as often, right? Since we can't run tests out-of-tree on the latest std/miri if miri's not building? But I agree the two are largely not connected.

If you want to invite me as an admin on this repository I can get the transfer going and then we can add the Zulip token as needed (I forget what exactly is needed there but we'll figure it out)

**Comment by RalfJung** [comment]
> Hm, it seems like subtree or not we'd run the tests just as often, right?

With Miri as a subtree we could actually always run the tests, even gate CI on that if we want.

> If you want to invite me as an admin on this repository

All right, will do. Thanks!

**Comment by Mark-Simulacrum** [comment]
I think I am a collaborator now but can't see the "settings" page -- maybe easier to just have you transfer the repository to me? Not sure. GitHub can be a bit finicky around this.

**Comment by RalfJung** [comment]
Adding you as a collaborator is the only option I found so far... I hoped it would let me then select an "admin" role for you but I can't see anything like that.

**Comment by RalfJung** [comment]
Okay admin permissions do not seem to be a thing (?!??), but I found a button to transfer ownership to you so maybe that works.

**Comment by Mark-Simulacrum** [comment]
OK, moved over -- maybe those are only for org-owned repos? Not sure.

I've configured the same two env variables as on rust-lang/miri (ZULIP_API_TOKEN and ZULIP_BOT_EMAIL) as secrets on this repository so a similar script to the cron job there should work here as well.

**Comment by RalfJung** [comment]
Awesome, thanks a lot! I'll look into setting up the GHA side of things.

In terms of permissions, it probably would make most sense to give the entire "miri" team full access to this repository.

**Comment by Mark-Simulacrum** [comment]
Switched access to the miri team (removed you as individual access, but that should hopefully be no big deal; you're on the miri team).

**Comment by Mark-Simulacrum** [comment]
@RalfJung One thing I noted -- this repository doesn't have LICENSE files quite yet. Looks like all of the commits are yours so you can probably just add those, would be good to do so before we get any external contributions :)

**Comment by RalfJung** [comment]
Ah, good point. I tend to forget about these legal things.^^

I assume I can just copy the license file(s) from the Miri repo?

**Comment by Mark-Simulacrum** [comment]
I'd use the ones from rust-lang/rust -- they're the most canonical ones we have. Looks like the miri ones actually have a copyright statement in the MIT file which (AIUI) may mean we need to replicate it when moving code out of the repository.

**Comment by RalfJung** [comment]
> I'd use the ones from rust-lang/rust

Kk, done.

**Comment by RalfJung** [comment]
I switched the config to GHA, so this should all work now. Thanks :)
