### ISSUE TITLE
looks like it hangs right before printing failures

### ISSUE THREAD

**Issue by matthiaskrgr** [rust-lang/miri-test-libstd#8]
I was running `./run-test.sh core --all-targets` with a couple of extra flags
````patch
diff --git a/run-test.sh b/run-test.sh
index a6a2841..8d4bc6d 100755
--- a/run-test.sh
+++ b/run-test.sh
@@ -32,6 +32,8 @@ export MIRI_LIB_SRC
 rm -f lib$CRATE
 ln -s "$MIRI_LIB_SRC"/$CRATE lib$CRATE

+export MIRIFLAGS="-Zmiri-check-number-validity -Zmiri-strict-provenance  -Zmiri-symbolic-alignment-check -Zmiri-tag-raw-pointers"
+
 # run test
 cd ./${CRATE}_miri_test
 cargo miri setup
 ````
 and after printing `failures:` it looked like the script/test execution was stuck.
 No further output was printed, I could watch the miri slowly eat more and more memory and I aborted it after reaching ~9-10 gigs.
 
 `perf top` showed a lot going on `miri::stacked_borrows::Stack`, wondering if we hit some kind of loop somehow
 ````
   47,29%  miri                                 [.] <miri::stacked_borrows::Stack>::access
  38,71%  miri                                 [.] <miri::stacked_borrows::Stack>::grant
   0,59%  [kernel]                             [k] mem_cgroup_iter
````
 

 `miri 0.1.0 (3b8b6aa 2022-05-06)`

**Comment by RalfJung** [comment]
Closing in favor of https://github.com/rust-lang/miri/issues/2273.
